-- Tabela de emails dos clientes

create table if not exists public.client_emails (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete cascade,
  email text not null,
  email_norm text generated always as (lower(btrim(email))) stored,
  is_primary boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists client_emails_email_norm_uidx on public.client_emails (email_norm);
create unique index if not exists client_emails_client_email_norm_uidx on public.client_emails (client_id, email_norm);
create index if not exists client_emails_client_id_idx on public.client_emails (client_id);

alter table public.client_emails enable row level security;

drop policy if exists "client_emails_select_auth" on public.client_emails;
drop policy if exists "client_emails_insert_auth" on public.client_emails;
drop policy if exists "client_emails_update_auth" on public.client_emails;
drop policy if exists "client_emails_delete_auth" on public.client_emails;

create policy "client_emails_select_auth" on public.client_emails
  for select to authenticated
  using (true);

create policy "client_emails_insert_auth" on public.client_emails
  for insert to authenticated
  with check (true);

create policy "client_emails_update_auth" on public.client_emails
  for update to authenticated
  using (true)
  with check (true);

create policy "client_emails_delete_auth" on public.client_emails
  for delete to authenticated
  using (true);

