-- Taskflow Reports - Supabase schema
-- Database-only layer (tables, constraints, RLS, policies, indexes)

begin;

-- Clients (clientes)
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text not null,
  cidade text not null,
  estado_uf text not null,
  uso_plataforma text,
  area_atuacao text not null,
  unidade text not null
);

alter table public.clients
  drop constraint if exists clients_cpf_digits_chk,
  drop constraint if exists clients_estado_uf_len_chk,
  drop constraint if exists clients_uso_plataforma_chk,
  drop constraint if exists clients_area_atuacao_chk;

alter table public.clients
  add constraint clients_cpf_digits_chk check (cpf ~ '^[0-9]{11}$'),
  add constraint clients_estado_uf_len_chk check (char_length(estado_uf) = 2),
  add constraint clients_uso_plataforma_chk check (
    uso_plataforma is null or uso_plataforma in ('Mobile', 'Web', 'Ambos', 'Não informado')
  ),
  add constraint clients_area_atuacao_chk check (
    area_atuacao in ('Saúde', 'Educação', 'Assistência Social', 'Outro')
  );

create unique index if not exists clients_cpf_uidx on public.clients (cpf);
create index if not exists clients_nome_idx on public.clients (nome);

-- Tickets (chamados)
create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  profissional_id uuid not null references auth.users (id),
  profissional_nome text not null,
  motivo text not null,
  motivo_outro_descricao text,
  prioridade text not null,
  data_atendimento date,
  retroativo boolean not null default false,
  retroativo_motivo text,
  client_id bigint not null references public.clients (id)
);

alter table public.tickets
  drop constraint if exists tickets_motivo_chk,
  drop constraint if exists tickets_motivo_outro_chk,
  drop constraint if exists tickets_prioridade_chk,
  drop constraint if exists tickets_retroativo_motivo_chk;

alter table public.tickets
  add constraint tickets_motivo_chk check (
    motivo in (
      'Alteração de Perfil',
      'Apresentação',
      'Atualização de dados cadastrais',
      'Auxílio em capacitações',
      'Cadastro não localizado',
      'Criação de documentos',
      'Dados divergentes',
      'Dúvida sobre uso do sistema',
      'Erro ao salvar informações',
      'Erro no sistema',
      'Eventos (auxílio)',
      'Funcionalidade indisponível',
      'Kanban/Power BI',
      'Problema de acesso',
      'Problema de cadastro',
      'Problemas com conexões e impressoras',
      'Recuperação de senha',
      'Sistema lento ou instável',
      'Solicitação de Cadastro',
      'Solicitação de informação',
      'Suporte remoto',
      'Suporte técnico',
      'Treinamento',
      'Workshop',
      'Outro'
    )
  ),
  add constraint tickets_motivo_outro_chk check (
    motivo <> 'Outro'
    or (motivo_outro_descricao is not null and btrim(motivo_outro_descricao) <> '')
  ),
  add constraint tickets_prioridade_chk check (prioridade in ('Baixa', 'Media', 'Alta')),
  add constraint tickets_retroativo_motivo_chk check (
    retroativo = false
    or (retroativo_motivo is not null and btrim(retroativo_motivo) <> '')
  );

create index if not exists tickets_client_id_idx on public.tickets (client_id);
create index if not exists tickets_profissional_id_idx on public.tickets (profissional_id);
create index if not exists tickets_created_at_idx on public.tickets (created_at);
create index if not exists tickets_data_atendimento_idx on public.tickets (data_atendimento);

-- Profiles (placeholder for future user metadata)
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  nome text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_auth_user_id_uidx on public.profiles (auth_user_id);

-- RLS
alter table public.clients enable row level security;
alter table public.tickets enable row level security;
alter table public.profiles enable row level security;

-- Policies: authenticated users can do everything
-- Clients

drop policy if exists "clients_select_auth" on public.clients;
drop policy if exists "clients_insert_auth" on public.clients;
drop policy if exists "clients_update_auth" on public.clients;
drop policy if exists "clients_delete_auth" on public.clients;

create policy "clients_select_auth" on public.clients
  for select to authenticated
  using (true);

create policy "clients_insert_auth" on public.clients
  for insert to authenticated
  with check (true);

create policy "clients_update_auth" on public.clients
  for update to authenticated
  using (true)
  with check (true);

create policy "clients_delete_auth" on public.clients
  for delete to authenticated
  using (true);

-- Tickets

drop policy if exists "tickets_select_auth" on public.tickets;
drop policy if exists "tickets_insert_auth" on public.tickets;
drop policy if exists "tickets_update_auth" on public.tickets;
drop policy if exists "tickets_delete_auth" on public.tickets;

create policy "tickets_select_auth" on public.tickets
  for select to authenticated
  using (true);

create policy "tickets_insert_auth" on public.tickets
  for insert to authenticated
  with check (true);

create policy "tickets_update_auth" on public.tickets
  for update to authenticated
  using (true)
  with check (true);

create policy "tickets_delete_auth" on public.tickets
  for delete to authenticated
  using (true);

-- Profiles

drop policy if exists "profiles_select_auth" on public.profiles;
drop policy if exists "profiles_insert_auth" on public.profiles;
drop policy if exists "profiles_update_auth" on public.profiles;
drop policy if exists "profiles_delete_auth" on public.profiles;

create policy "profiles_select_auth" on public.profiles
  for select to authenticated
  using (true);

create policy "profiles_insert_auth" on public.profiles
  for insert to authenticated
  with check (true);

create policy "profiles_update_auth" on public.profiles
  for update to authenticated
  using (true)
  with check (true);

create policy "profiles_delete_auth" on public.profiles
  for delete to authenticated
  using (true);

commit;

