-- Taskflow Reports - Supabase schema
-- Database-only layer (tables, constraints, RLS, policies, indexes)

begin;

-- Clients (clientes)
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text not null,
  cidade text not null,
  estado_uf text not null,
  uso_plataforma text,
  area_atuacao text not null,
  unidade text not null,
  multi_unidade boolean not null default false
);

alter table public.clients
  add column if not exists multi_unidade boolean not null default false;

alter table public.clients
  drop constraint if exists clients_cpf_digits_chk,
  drop constraint if exists clients_estado_uf_len_chk,
  drop constraint if exists clients_uso_plataforma_chk,
  drop constraint if exists clients_area_atuacao_chk,
  drop constraint if exists clients_unidade_not_blank_chk;

alter table public.clients
  add constraint clients_cpf_digits_chk check (cpf ~ '^[0-9]{11}$'),
  add constraint clients_estado_uf_len_chk check (char_length(estado_uf) = 2),
  add constraint clients_uso_plataforma_chk check (
    uso_plataforma is null or uso_plataforma in ('Mobile', 'Web', 'Ambos', 'Não informado')
  ),
  add constraint clients_area_atuacao_chk check (
    area_atuacao in ('Saúde', 'Educação', 'Assistência Social', 'Outro')
  ),
  add constraint clients_unidade_not_blank_chk check (btrim(unidade) <> '');

create unique index if not exists clients_cpf_uidx on public.clients (cpf);
create index if not exists clients_nome_idx on public.clients (nome);
create index if not exists idx_clients_area_atuacao on public.clients (area_atuacao);

-- Client Emails
create table if not exists public.client_emails (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete cascade,
  email text not null,
  email_norm text generated always as (lower(btrim(email))) stored,
  is_primary boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists client_emails_email_norm_uidx on public.client_emails (email_norm);
create unique index if not exists client_emails_client_email_norm_uidx on public.client_emails (client_id, email_norm);
create index if not exists client_emails_client_id_idx on public.client_emails (client_id);

-- Tickets (chamados)
create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  profissional_id uuid not null references auth.users (id),
  profissional_nome text not null,
  motivo text,
  motivo_outro_descricao text,
  prioridade text,
  data_atendimento date,
  retroativo boolean not null default false,
  retroativo_motivo text,
  uso_plataforma text,
  client_id bigint references public.clients (id),
  unidade text,
  status text not null default 'ABERTO'
);

alter table public.tickets
  add column if not exists unidade text,
  add column if not exists uso_plataforma text;

alter table public.tickets
  drop constraint if exists tickets_motivo_chk,
  drop constraint if exists tickets_motivo_outro_chk,
  drop constraint if exists tickets_prioridade_chk,
  drop constraint if exists tickets_retroativo_motivo_chk,
  drop constraint if exists tickets_uso_plataforma_chk,
  drop constraint if exists tickets_unidade_not_blank_chk,
  drop constraint if exists tickets_unidade_not_blank_check,
  drop constraint if exists tickets_status_chk;

alter table public.tickets
  add constraint tickets_motivo_chk check (
    motivo is null or motivo in (
      'Alteração de Perfil',
      'Apresentação',
      'Atualização de dados cadastrais',
      'Auxílio em capacitações',
      'Cadastro não localizado',
      'Criação de documentos',
      'Dados divergentes',
      'Dúvida sobre uso do sistema',
      'Erro ao salvar informações',
      'Erro no sistema',
      'Eventos (auxílio)',
      'Funcionalidade indisponível',
      'Kanban/Power BI',
      'Problema de acesso',
      'Problema de cadastro',
      'Problemas com conexões e impressoras',
      'Recuperação de senha',
      'Sistema lento ou instável',
      'Solicitação de Cadastro',
      'Solicitação de informação',
      'Suporte remoto',
      'Suporte técnico',
      'Treinamento',
      'Workshop',
      'Outro'
    )
  ),
  add constraint tickets_prioridade_chk check (
    prioridade is null or prioridade in ('Baixa', 'Media', 'Alta')
  ),
  add constraint tickets_status_chk check (
    status in ('ABERTO', 'EM_ANDAMENTO', 'AGUARDANDO', 'RESOLVIDO', 'CANCELADO')
  ),
  add constraint tickets_retroativo_motivo_chk check (
    retroativo = false
    or (retroativo_motivo is not null and btrim(retroativo_motivo) <> '')
  ),
  add constraint tickets_uso_plataforma_chk check (
    uso_plataforma is null or uso_plataforma in ('Mobile', 'Web', 'Ambos', 'Não informado')
  ),
  add constraint tickets_unidade_not_blank_chk check (
    unidade is null or btrim(unidade) <> ''
  );

create index if not exists tickets_client_id_idx on public.tickets (client_id);
create index if not exists tickets_profissional_id_idx on public.tickets (profissional_id);
create index if not exists tickets_created_at_idx on public.tickets (created_at);
create index if not exists tickets_data_atendimento_idx on public.tickets (data_atendimento);
create index if not exists idx_tickets_unidade on public.tickets (unidade);

-- Ticket Motivos (itens)
create table if not exists public.ticket_motivos (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets (id) on delete cascade,
  client_id bigint references public.clients (id),
  unidade text,
  uso_plataforma text,
  prioridade text not null default 'Baixa',
  motivo text not null,
  motivo_outro_descricao text,
  status text not null default 'ABERTO',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ticket_motivos
  drop constraint if exists ticket_motivos_motivo_chk,
  drop constraint if exists ticket_motivos_motivo_outro_chk,
  drop constraint if exists ticket_motivos_status_chk,
  drop constraint if exists ticket_motivos_prioridade_chk;

alter table public.ticket_motivos
  add constraint ticket_motivos_motivo_chk check (
    motivo in (
      'Alteração de Perfil',
      'Apresentação',
      'Atualização de dados cadastrais',
      'Auxílio em capacitações',
      'Cadastro não localizado',
      'Criação de documentos',
      'Dados divergentes',
      'Dúvida sobre uso do sistema',
      'Erro ao salvar informações',
      'Erro no sistema',
      'Eventos (auxílio)',
      'Funcionalidade indisponível',
      'Kanban/Power BI',
      'Problema de acesso',
      'Problema de cadastro',
      'Problemas com conexões e impressoras',
      'Recuperação de senha',
      'Sistema lento ou instável',
      'Solicitação de Cadastro',
      'Solicitação de informação',
      'Suporte remoto',
      'Suporte técnico',
      'Treinamento',
      'Workshop',
      'Outro'
    )
  ),
  add constraint ticket_motivos_motivo_outro_chk check (
    motivo <> 'Outro'
    or (motivo_outro_descricao is not null and btrim(motivo_outro_descricao) <> '')
  ),
  add constraint ticket_motivos_prioridade_chk check (
    prioridade in ('Baixa', 'Media', 'Alta')
  ),
  add constraint ticket_motivos_status_chk check (
    status in ('ABERTO', 'EM_ANDAMENTO', 'AGUARDANDO', 'RESOLVIDO', 'CANCELADO')
  );

create index if not exists ticket_motivos_ticket_id_idx on public.ticket_motivos (ticket_id);
create index if not exists ticket_motivos_client_id_idx on public.ticket_motivos (client_id);

-- Units (unidades)
create table if not exists public.units (
  id bigint generated by default as identity primary key,
  unit_name text,
  name_status text not null default 'INFORMADO',
  name_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.units
  alter column unit_name drop not null;

alter table public.units
  drop constraint if exists check_name_status_valid,
  drop constraint if exists check_name_logic;

alter table public.units
  add constraint check_name_status_valid check (
    name_status in ('INFORMADO', 'NAO_INFORMADO', 'NAO_ENCONTRADO', 'SEM_NOME')
  ),
  add constraint check_name_logic check (
    (name_status = 'INFORMADO' and unit_name is not null)
    or (name_status <> 'INFORMADO' and unit_name is null)
  );

-- Profiles (placeholder for future user metadata)
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  nome text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_auth_user_id_uidx on public.profiles (auth_user_id);

-- RLS
alter table public.clients enable row level security;
alter table public.tickets enable row level security;
alter table public.client_emails enable row level security;
alter table public.ticket_motivos enable row level security;
alter table public.units enable row level security;
alter table public.profiles enable row level security;

-- Policies: authenticated users can do everything
-- Clients

drop policy if exists "clients_select_auth" on public.clients;
drop policy if exists "clients_insert_auth" on public.clients;
drop policy if exists "clients_update_auth" on public.clients;
drop policy if exists "clients_delete_auth" on public.clients;

create policy "clients_select_auth" on public.clients
  for select to authenticated
  using (true);

create policy "clients_insert_auth" on public.clients
  for insert to authenticated
  with check (true);

create policy "clients_update_auth" on public.clients
  for update to authenticated
  using (true)
  with check (true);

create policy "clients_delete_auth" on public.clients
  for delete to authenticated
  using (true);

-- Tickets

drop policy if exists "tickets_select_auth" on public.tickets;
drop policy if exists "tickets_insert_auth" on public.tickets;
drop policy if exists "tickets_update_auth" on public.tickets;
drop policy if exists "tickets_delete_auth" on public.tickets;

create policy "tickets_select_auth" on public.tickets
  for select to authenticated
  using (true);

create policy "tickets_insert_auth" on public.tickets
  for insert to authenticated
  with check (true);

create policy "tickets_update_auth" on public.tickets
  for update to authenticated
  using (true)
  with check (true);

create policy "tickets_delete_auth" on public.tickets
  for delete to authenticated
  using (true);

-- Ticket Motivos

drop policy if exists "ticket_motivos_select_auth" on public.ticket_motivos;
drop policy if exists "ticket_motivos_insert_auth" on public.ticket_motivos;
drop policy if exists "ticket_motivos_update_auth" on public.ticket_motivos;
drop policy if exists "ticket_motivos_delete_auth" on public.ticket_motivos;

create policy "ticket_motivos_select_auth" on public.ticket_motivos
  for select to authenticated
  using (true);

create policy "ticket_motivos_insert_auth" on public.ticket_motivos
  for insert to authenticated
  with check (true);

create policy "ticket_motivos_update_auth" on public.ticket_motivos
  for update to authenticated
  using (true)
  with check (true);

create policy "ticket_motivos_delete_auth" on public.ticket_motivos
  for delete to authenticated
  using (true);

-- Client Emails

drop policy if exists "client_emails_select_auth" on public.client_emails;
drop policy if exists "client_emails_insert_auth" on public.client_emails;
drop policy if exists "client_emails_update_auth" on public.client_emails;
drop policy if exists "client_emails_delete_auth" on public.client_emails;

create policy "client_emails_select_auth" on public.client_emails
  for select to authenticated
  using (true);

create policy "client_emails_insert_auth" on public.client_emails
  for insert to authenticated
  with check (true);

create policy "client_emails_update_auth" on public.client_emails
  for update to authenticated
  using (true)
  with check (true);

create policy "client_emails_delete_auth" on public.client_emails
  for delete to authenticated
  using (true);

-- Units

drop policy if exists "units_select_auth" on public.units;
drop policy if exists "units_insert_auth" on public.units;
drop policy if exists "units_update_auth" on public.units;
drop policy if exists "units_delete_auth" on public.units;

create policy "units_select_auth" on public.units
  for select to authenticated
  using (true);

create policy "units_insert_auth" on public.units
  for insert to authenticated
  with check (true);

create policy "units_update_auth" on public.units
  for update to authenticated
  using (true)
  with check (true);

create policy "units_delete_auth" on public.units
  for delete to authenticated
  using (true);

-- Profiles

drop policy if exists "profiles_select_auth" on public.profiles;
drop policy if exists "profiles_insert_auth" on public.profiles;
drop policy if exists "profiles_update_auth" on public.profiles;
drop policy if exists "profiles_delete_auth" on public.profiles;

create policy "profiles_select_auth" on public.profiles
  for select to authenticated
  using (true);

create policy "profiles_insert_auth" on public.profiles
  for insert to authenticated
  with check (true);

create policy "profiles_update_auth" on public.profiles
  for update to authenticated
  using (true)
  with check (true);

create policy "profiles_delete_auth" on public.profiles
  for delete to authenticated
  using (true);

commit;
