-- Estrutura da tabela ticket_motivos (itens do ticket geral)

create table if not exists public.ticket_motivos (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets (id) on delete cascade,
  client_id bigint references public.clients (id),
  unidade text,
  uso_plataforma text,
  prioridade text not null default 'Baixa',
  motivo text not null,
  motivo_outro_descricao text,
  status text not null default 'ABERTO',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ticket_motivos
  drop constraint if exists ticket_motivos_motivo_chk,
  drop constraint if exists ticket_motivos_motivo_outro_chk,
  drop constraint if exists ticket_motivos_status_chk,
  drop constraint if exists ticket_motivos_prioridade_chk;

alter table public.ticket_motivos
  add constraint ticket_motivos_motivo_chk check (
    motivo in (
      'Alteração de Perfil',
      'Apresentação',
      'Atualização de dados cadastrais',
      'Auxílio em capacitações',
      'Cadastro não localizado',
      'Criação de documentos',
      'Dados divergentes',
      'Dúvida sobre uso do sistema',
      'Erro ao salvar informações',
      'Erro no sistema',
      'Eventos (auxílio)',
      'Funcionalidade indisponível',
      'Kanban/Power BI',
      'Problema de acesso',
      'Problema de cadastro',
      'Problemas com conexões e impressoras',
      'Recuperação de senha',
      'Sistema lento ou instável',
      'Solicitação de Cadastro',
      'Solicitação de informação',
      'Suporte remoto',
      'Suporte técnico',
      'Treinamento',
      'Workshop',
      'Outro'
    )
  ),
  add constraint ticket_motivos_motivo_outro_chk check (
    motivo <> 'Outro'
    or (motivo_outro_descricao is not null and btrim(motivo_outro_descricao) <> '')
  ),
  add constraint ticket_motivos_prioridade_chk check (
    prioridade in ('Baixa', 'Media', 'Alta')
  ),
  add constraint ticket_motivos_status_chk check (
    status in ('ABERTO', 'EM_ANDAMENTO', 'AGUARDANDO', 'RESOLVIDO', 'CANCELADO')
  );

create index if not exists ticket_motivos_ticket_id_idx on public.ticket_motivos (ticket_id);
create index if not exists ticket_motivos_client_id_idx on public.ticket_motivos (client_id);

alter table public.ticket_motivos enable row level security;

drop policy if exists "ticket_motivos_select_auth" on public.ticket_motivos;
drop policy if exists "ticket_motivos_insert_auth" on public.ticket_motivos;
drop policy if exists "ticket_motivos_update_auth" on public.ticket_motivos;
drop policy if exists "ticket_motivos_delete_auth" on public.ticket_motivos;

create policy "ticket_motivos_select_auth" on public.ticket_motivos
  for select to authenticated
  using (true);

create policy "ticket_motivos_insert_auth" on public.ticket_motivos
  for insert to authenticated
  with check (true);

create policy "ticket_motivos_update_auth" on public.ticket_motivos
  for update to authenticated
  using (true)
  with check (true);

create policy "ticket_motivos_delete_auth" on public.ticket_motivos
  for delete to authenticated
  using (true);
